language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
     - sudo apt-get install python-pip -qq
     - sudo apt-get install -qq coreutils
     - sudo apt-get install -qq build-essential libssl-dev libffi-dev python-dev python-pip
     - sudo pip install crossbar

before_script:
    - composer install
    - sh tests/Crossbar/travis_install

script:
    - php tests/TestServer.php 15 & phpunit
    - sh tests/Crossbar/run_tests

